### PR TITLE
CRAN package but need the dev GitHub version

### PR DESCRIPTION
**Pull request by cjyetman**

### CODE REVIEW

**Review by jdhoffa — CHANGES_REQUESTED** [review]
Can you ensure the script will fail if the WRONG version is installed?

**Comment by cjyetman** [comment]
> Can you ensure the script will fail if the WRONG version is installed?

yeah, I know it might be hard, and probably change frequently, so I haven't figured that out yet, but.... conceptually I think this is something we should test for

**Comment by cjyetman** [comment]
add this test for > latest CRAN version of dbplyr
```r
if (!packageVersion("dbplyr") > pkgsearch::cran_package("dbplyr")$Version) {
  stop("Please install the dev version of dbplyr")
}
```

**Review by jdhoffa — APPROVED** [review]
lgtm

**Pull request merged**
